import type { Metadata } from 'next'
import { HomeService } from '@/services'

import { Poppins } from 'next/font/google'
import { Footer, Header } from '@/components'

import '../styles/global.css'

const poppins = Poppins({
  subsets: ['devanagari'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { home } = await HomeService();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="container">
          <Header home={home} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
