import '../styles/global.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Header, Footer } from '../components'

const poppins = Poppins({ subsets: ['devanagari'], weight: ['300', '400', '500', '600', '700', '800', '900'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="container">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
